Vagrant.configure("2") do |config|
    config.vm.box = "gusztavvargadr/windows-10"
    config.vm.box_check_update = false
    
    config.vm.network "public_network", use_dhcp_assigned_default_route: true
    config.vm.network "forwarded_port", guest: 5000, host: 5000

    config.vm.provider "virtualbox" do |vb|
      vb.memory = "6144"
      vb.cpus = 2
      config.vm.boot_timeout = 1200
    end
  
    config.vm.provision "file", source: "../../nuget/nuget.config", destination: "C:/Users/vagrant/nuget.config"
    
    config.vm.provision "shell", inline: <<-SHELL
        Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
        
        choco install dotnet-6.0-sdk -y

        $env:Path += ";C:\\Program Files\\dotnet"
        [System.Environment]::SetEnvironmentVariable("Path", $env:Path, [System.EnvironmentVariableTarget]::Machine)

        dotnet tool install --global dserhiichuk --version 1.0.0 --configfile C:/Users/vagrant/nuget.config
    SHELL
end
  