Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.box_check_update = false
    
    config.vm.network "public_network", use_dhcp_assigned_default_route: true
    config.vm.network "forwarded_port", guest: 3000, host: 5000

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "6144"
        vb.cpus = 2
        config.vm.boot_timeout = 1200
    end

    config.vm.synced_folder ".", "/home/vagrant/Lab_5", type: "virtualbox"
    config.vm.synced_folder "../LabLib", "/home/vagrant/LabLib", type: "virtualbox"
    
    config.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update -y
        sudo apt-get install -y wget apt-transport-https software-properties-common
        
        wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        rm packages-microsoft-prod.deb

        sudo apt-get update
        sudo apt-get install -y dotnet-sdk-6.0

        echo 'export PATH=$PATH:$HOME/.dotnet/tools' >> ~/.bashrc
        export PATH=$PATH:$HOME/.dotnet/tools

        cd /home/vagrant/Lab_5
        dotnet run Lab_5.csproj
    SHELL
end
