Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.box_check_update = false
    
    config.vm.network "public_network", use_dhcp_assigned_default_route: true
    config.vm.network "forwarded_port", guest: 3000, host: 3000
    config.vm.network "forwarded_port", guest: 3001, host: 3001

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "6144"
        vb.cpus = 2
        config.vm.boot_timeout = 1200
    end

    config.vm.synced_folder ".", "/vagrant/Lab_6", type: "virtualbox"
    config.vm.synced_folder "../Lab_5", "/vagrant/Lab_5", type: "virtualbox"
    config.vm.synced_folder "../LabLib", "/vagrant/LabLib", type: "virtualbox"

    config.vm.provision "init", type: "shell", path: "./init-provision.sh"
  
    config.vm.provision "postgre", type: "shell", path: "./postgre-provision.sh"
    config.vm.provision "sqlserver", type: "shell", path: "./sqlserver-provision.sh"
    config.vm.provision "sqlite", type: "shell", path: "./sqlite-provision.sh"
end
